### ISSUE TITLE
Investigage the use of --no-site-packages for fermentrack venv

### ISSUE THREAD

**Issue by stone** [thorrak/fermentrack-tools#21]
Investigate the possibility to use --no-site-packages for fermentrack virtual environment, one user using raspberry pixel. The installation script complained on an already installed version of python-zmq.

With the option --no-site-packages distribution packages will not interfere with fermentrack dependencies.

**Comment by stone** [comment]
Verified that install works as before with option above, will try to test with zmq locally installed and see if it conflicts when option enabled.

**Comment by stone** [comment]
Now tested a lot more, distribution packages does not interfere with our installation. So I don't think this is an issue, got a install.log report from a user and it was ok (warnings about old zmq local version only)
I'll close this one.

**Comment by thorrak** [comment]
In your testing did you see any issues using the no site packages option? If not, I figure we might as well use it. 

Fewer errors - even if there is no impact - are better than more.

**Comment by stone** [comment]
Yes, I think its a good idea to use that switch, then no distribution packages will interfere with Fermentracks deps.
