### ISSUE TITLE
force-pip-install.sh missing execute permmision

### ISSUE THREAD

**Issue by M-Spetz** [thorrak/fermentrack-tools#37]
I tried to install Fermentrack on a new Ubuntu server. After he installation the webserver just prompted a 502 message. I reinstalled  the server, cloned the reposetory, added execute permission on force-pip-install.sh with chmod. After that the installation worked.

![image](https://user-images.githubusercontent.com/35556819/72893608-b813bf00-3d19-11ea-9e5d-1df9dcf41ea4.png)

**Comment by M-Spetz** [comment]
I close this issue, as i have created a pull request that fixes the issue.

Pull request: [https://github.com/thorrak/fermentrack-tools/pull/38](https://github.com/thorrak/fermentrack-tools/pull/38)

**Comment by thorrak** [comment]
Reopening pending merge of PR
