### ISSUE TITLE
Numpy package not available

### ISSUE THREAD

**Issue by modul8** [thorrak/fermentrack-tools#41]
Hi. Im trying to calibrate an ispindel but getting an error message 
The "numpy" python package is not available which is required for calibration
I have updated my fermentrack with your python update script and have tried updating fermentrack to the dev channel but still getting the error. I had already updated the python script before i tried calibrating the ispindel.

**Comment by thorrak** [comment]
FYI - I'm moving this issue to the fermentrack-tools repo as this is an issue with the environment scripts. Give me a second and I'll get a fix pushed out.

**Comment by thorrak** [comment]
Ok, the fix should be live - you will need to re-run the `fix-environment.sh` script in order to get it to work:
`curl -L "https://raw.githubusercontent.com/thorrak/fermentrack-tools/master/fix-environment.sh" | sudo bash`

The tweak forces numpy to be compiled from scratch into your environment which should guarantee a working version (at the one-time expense of it taking ~10 minutes or so to compile). 

I've tested this on _new_ installs on both stretch and buster, but haven't tested on _existing_ installs - let me know if this works for you and I'll close out the issue.

**Comment by modul8** [comment]
`      Successfully uninstalled PyBluez-0.23
    Running setup.py install for PyBluez ... done
  Attempting uninstall: aioblescan
    Found existing installation: aioblescan 0.2.6
    Uninstalling aioblescan-0.2.6:
      Successfully uninstalled aioblescan-0.2.6
Successfully installed Django-3.0.6 GitPython-3.1.2
 PyBluez-0.23 aioblescan-0.2.6 asgiref-3.2.7 certif
i-2020.4.5.1 chardet-3.0.4 chaussette-1.3.0 circus-
0.16.1 configobj-5.0.6 django-constance-2.6.0 djang
o-picklefield-2.1.1 ecdsa-0.15 esptool-2.8 gitdb-4.
0.5 huey-2.2.0 idna-2.9 ifaddr-0.1.6 packaging-17.1
 pid-3.0.3 psutil-5.7.0 pyaes-1.6.1 pyparsing-2.4.7
 pyserial-3.4 pytz-2020.1 pyudev-0.22.0 pyzmq-19.0.
1 redis-3.4.1 requests-2.23.0 sentry-sdk-0.14.4 six
-1.15.0 smmap-3.0.4 sqlparse-0.3.1 tornado-4.5.3 ur
llib3-1.25.9 zeroconf-0.26.2
Running manage.py migrate/fix_sqlite_for_django_2/c
ollectstatic...
Operations to perform:
  Apply all migrations: admin, app, auth, contentty
pes, database, external_push, firmware_flash, gravi
ty, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflect
ed in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrat
ions, and then re-run 'manage.py migrate' to apply
them.
Operations to perform:
  Apply all migrations: admin, app, auth, contentty
pes, database, external_push, firmware_flash, gravi
ty, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflect
ed in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrat
ions, and then re-run 'manage.py migrate' to apply
them.
Clearing firmware_flash.Firmware objects...
Clearing firmware_flash.Board objects...
Clearing firmware_flash.DeviceFamily objects...
Clearing firmware_flash.Project objects...
Done clearing firmware_flash objects...
Rebuilding app Administration...
Rebuilding model <class 'django.contrib.admin.model
s.LogEntry'>
Rebuilding app Authentication and Authorization...
Rebuilding model <class 'django.contrib.auth.models
.Permission'>
Rebuilding model <class 'django.contrib.auth.models
.Group_permissions'>
Rebuilding model <class 'django.contrib.auth.models
.Group'>
Rebuilding model <class 'django.contrib.auth.models
.User_groups'>
Rebuilding model <class 'django.contrib.auth.models
.User_user_permissions'>
Rebuilding model <class 'django.contrib.auth.models
.User'>
Rebuilding app Content Types...
Rebuilding model <class 'django.contrib.contenttype
s.models.ContentType'>
Rebuilding app Sessions...
Rebuilding model <class 'django.contrib.sessions.mo
dels.Session'>
Rebuilding app Messages...
Rebuilding app Static Files...
Rebuilding app App...
Rebuilding model <class 'app.models.BrewPiDevice'>
Rebuilding model <class 'app.models.Beer'>
Rebuilding model <class 'app.models.FermentationPro
file'>
Rebuilding model <class 'app.models.FermentationPro
filePoint'>
Rebuilding model <class 'app.models.OldControlConst
ants'>
Rebuilding model <class 'app.models.NewControlConst
ants'>
Rebuilding app Firmware_Flash...
Rebuilding model <class 'firmware_flash.models.Devi
ceFamily'>
Rebuilding model <class 'firmware_flash.models.Firm
ware'>
Rebuilding model <class 'firmware_flash.models.Boar
d'>
Rebuilding model <class 'firmware_flash.models.Flas
hRequest'>
Rebuilding model <class 'firmware_flash.models.Proj
ect'>
Rebuilding app Gravity...
Rebuilding model <class 'gravity.models.GravitySens
or'>
Rebuilding model <class 'gravity.models.GravityLog'
>
Rebuilding model <class 'gravity.models.TiltTempCal
ibrationPoint'>
Rebuilding model <class 'gravity.models.TiltGravity
CalibrationPoint'>
Rebuilding model <class 'gravity.models.TiltConfigu
ration'>
Rebuilding model <class 'gravity.models.TiltBridge'
>
Rebuilding model <class 'gravity.models.IspindelGra
vityCalibrationPoint'>
Rebuilding model <class 'gravity.models.IspindelCon
figuration'>
Rebuilding app External_Push...
Rebuilding model <class 'external_push.models.Gener
icPushTarget_brewpi_to_push'>
Rebuilding model <class 'external_push.models.Gener
icPushTarget_gravity_sensors_to_push'>
Rebuilding model <class 'external_push.models.Gener
icPushTarget'>
Rebuilding model <class 'external_push.models.Brewe
rsFriendPushTarget'>
Rebuilding model <class 'external_push.models.Brewf
atherPushTarget'>
Rebuilding model <class 'external_push.models.Thing
SpeakPushTarget'>
Rebuilding model <class 'external_push.models.Grain
fatherPushTarget'>
Rebuilding app Constance...
Rebuilding app Database...
Rebuilding model <class 'constance.backends.databas
e.models.Constance'>
Rebuilding app Djhuey...
Completed app rebuilding - running check_constraint
s to ensure we're in a consistent state.
Rebuild complete!
Quitting Circus
ok
Calling updateCronCircus to restart Circus...
Starting Fermentrack supervisor: circusd: done

Done! Exiting.
pi@raspberrypi:~ $
pi@raspberrypi:~ $
`

**Comment by modul8** [comment]
Unfortunately still the same error

**Comment by modul8** [comment]
Sorry. Didn't grab the whole output from ssh. Is there a log you would like?

**Comment by thorrak** [comment]
No - I think this is a case of me being too cute for my own good. Let me recheck but I think I may have disabled the line of code you need if Python is already installed.

**Comment by modul8** [comment]
I saw your commit from yesterday so tried running the script again. I still get the numpy package not available error. Not sure if this should be fixed or not?

**Comment by thorrak** [comment]
Which script did you try to run, and what version of Raspbian are you using?

**Comment by modul8** [comment]
The same one i ran at the beginning of this issue i posted

curl -L "https://raw.githubusercontent.com/thorrak/fermentrack-tools/master/fix-environment.sh" | sudo bash

Im on stretch. If i try to calibrate an ispindel i get an error that numpy is not available

**Comment by modul8** [comment]
Any pointers on how i would go about getting numpy manually? I have upgraded to the latest fermentrack and run the fix-environment script a few times but am still unable to calibrate an ispindel due to numpy being unavailable. 
Thank you

**Comment by modul8** [comment]
)
Looking in indexes: https://pypi.org/simple, https:
//www.piwheels.org/simple
Requirement already satisfied: numpy==1.18.4 in ./v
env/lib/python3.7/site-packages (1.18.4)

::: Making sure everything is owned by fermentrack

Just a snippet from when i run fix-environment

**Comment by thorrak** [comment]
I didn't mean to close this with that PR, but this _should_ be fixed.

**Comment by modul8** [comment]
Worked like a charm! Thank you very much!

**Comment by thorrak** [comment]
Perfect! Thanks!
